language: cpp
compiler:
  - g++
services:
    - mongodb
script:
    - mongo --version
    - mkdir build && cd build
    - cmake ..
    - make
    - make test
branches:
  only:
    - master
notifications:
  recipients:
    - virako.9@gmail.com
  email:
    on_success: change
    on_failure: always
before_install:
  - sudo apt-get install cmake libboost-all-dev libirrlicht-dev
