language: cpp
compiler:
  - gcc
script:
    mkdir build && cd build
    cmake ..
    make
    make test
branches:
  only:
    - master
notifications:
  recipients:
    - virako.9@gmail.com
  email:
    on_success: change
    on_failure: always
before_install:
  - sudo apt-get install cmake libboost-test1.49.0 # irrlicht
