language: cpp
compiler:
  - gcc
script: rake
branches:
  only:
    - master
notifications:
  recipients:
    - virako.9@gmail.com
  email:
    on_success: change
    on_failure: always
rvm:
  - 1.8.7
  - 1.9.3
before_install:
  - sudo apt-get install cmake
